-- RiseLooter CPX reward ledger.
-- New users start at 0 RL Coins / 0 XP; level 1 is derived from 0 XP in the UI.
-- 70% of validated CPX revenue is credited to the user as RL Coins.
-- Validated CPX rewards also grant XP; reversals remove both exactly once.
-- 30% is reserved for the publisher and stored per transaction for admin accounting.

-- Harden the canonical profile starting state without resetting existing earned balances.
update public.profiles set lootix_available = 0 where lootix_available is null;
update public.profiles set xp = 0 where xp is null;
alter table public.profiles alter column lootix_available set default 0;
alter table public.profiles alter column xp set default 0;
alter table public.profiles alter column lootix_available set not null;
alter table public.profiles alter column xp set not null;

create table if not exists public.partner_reward_transactions (
  id bigint generated by default as identity primary key,
  provider text not null,
  transaction_id text not null,
  user_id uuid not null,
  offer_id text,
  status text not null,
  amount_usd numeric(12,6) not null default 0,
  user_share_usd numeric(12,6) not null default 0,
  publisher_share_usd numeric(12,6) not null default 0,
  reward_coins bigint not null default 0,
  reward_xp bigint not null default 0,
  credited boolean not null default false,
  reversed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(provider, transaction_id)
);

-- Safe upgrades for databases where the table already existed.
alter table public.partner_reward_transactions add column if not exists user_share_usd numeric(12,6) not null default 0;
alter table public.partner_reward_transactions add column if not exists publisher_share_usd numeric(12,6) not null default 0;
alter table public.partner_reward_transactions add column if not exists reward_xp bigint not null default 0;

update public.partner_reward_transactions
set user_share_usd = round(amount_usd * 0.70, 6),
    publisher_share_usd = round(amount_usd * 0.30, 6)
where user_share_usd = 0 and publisher_share_usd = 0 and amount_usd > 0;

-- Existing historical credits keep their previous accounting. XP is only awarded by
-- a newly validated callback after this rule is installed; there is no retroactive XP grant.

alter table public.partner_reward_transactions enable row level security;
-- No client policies: only service-role/server access.

create or replace function public.apply_partner_reward(
  p_provider text,
  p_transaction_id text,
  p_user_id uuid,
  p_offer_id text,
  p_status text,
  p_amount_usd numeric,
  p_reward_coins bigint
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  tx public.partner_reward_transactions%rowtype;
  delta bigint := 0;
  xp_delta bigint := 0;
  owner_delta numeric(12,6) := 0;
  calc_user_share numeric(12,6) := round(greatest(coalesce(p_amount_usd,0),0) * 0.70, 6);
  calc_publisher_share numeric(12,6) := round(greatest(coalesce(p_amount_usd,0),0) * 0.30, 6);
  calc_reward_xp bigint := case when coalesce(p_amount_usd,0) > 0 then greatest(1, coalesce(p_reward_coins,0)) else 0 end;
begin
  if p_provider <> 'cpx' then raise exception 'unsupported provider'; end if;
  if p_transaction_id is null or length(p_transaction_id) = 0 then raise exception 'missing transaction id'; end if;
  if p_reward_coins < 0 then raise exception 'invalid reward'; end if;
  if p_amount_usd < 0 then raise exception 'invalid amount'; end if;

  insert into public.partner_reward_transactions(
    provider, transaction_id, user_id, offer_id, status, amount_usd,
    user_share_usd, publisher_share_usd, reward_coins, reward_xp
  )
  values (
    p_provider, p_transaction_id, p_user_id, p_offer_id, p_status, p_amount_usd,
    calc_user_share, calc_publisher_share, p_reward_coins, calc_reward_xp
  )
  on conflict (provider, transaction_id) do nothing;

  select * into tx from public.partner_reward_transactions
   where provider=p_provider and transaction_id=p_transaction_id
   for update;

  if tx.user_id <> p_user_id then raise exception 'transaction user mismatch'; end if;

  if p_status = '1' and not tx.credited and not tx.reversed then
    update public.profiles
       set lootix_available = coalesce(lootix_available,0) + tx.reward_coins,
           xp = coalesce(xp,0) + tx.reward_xp
     where id = tx.user_id;
    if not found then raise exception 'user profile not found'; end if;

    delta := tx.reward_coins;
    xp_delta := tx.reward_xp;
    owner_delta := tx.publisher_share_usd;

    update public.partner_reward_transactions
       set credited=true, status=p_status, updated_at=now()
     where id=tx.id;

  elsif p_status = '2' and tx.credited and not tx.reversed then
    update public.profiles
       set lootix_available = greatest(0, coalesce(lootix_available,0) - tx.reward_coins),
           xp = greatest(0, coalesce(xp,0) - tx.reward_xp)
     where id = tx.user_id;
    if not found then raise exception 'user profile not found'; end if;

    delta := -tx.reward_coins;
    xp_delta := -tx.reward_xp;
    owner_delta := -tx.publisher_share_usd;

    update public.partner_reward_transactions
       set reversed=true, status=p_status, updated_at=now()
     where id=tx.id;

  elsif p_status = '2' and not tx.credited and not tx.reversed then
    -- A reversal can arrive before a credit because partner callbacks may be delayed/reordered.
    -- Persist that terminal state so a late status=1 callback cannot credit Coins or XP.
    update public.partner_reward_transactions
       set reversed=true, status=p_status, updated_at=now()
     where id=tx.id;
  else
    update public.partner_reward_transactions
       set status=p_status, updated_at=now()
     where id=tx.id;
  end if;

  return jsonb_build_object(
    'ok', true,
    'transaction_id', p_transaction_id,
    'user_reward_coins_delta', delta,
    'user_xp_delta', xp_delta,
    'publisher_share_usd_delta', owner_delta,
    'user_share_usd', tx.user_share_usd,
    'publisher_share_usd', tx.publisher_share_usd
  );
end;
$$;

revoke all on function public.apply_partner_reward(text,text,uuid,text,text,numeric,bigint) from public;
revoke all on function public.apply_partner_reward(text,text,uuid,text,text,numeric,bigint) from anon;
revoke all on function public.apply_partner_reward(text,text,uuid,text,text,numeric,bigint) from authenticated;
grant execute on function public.apply_partner_reward(text,text,uuid,text,text,numeric,bigint) to service_role;
