-- RiseLooter CPX reward ledger. Run once in Supabase SQL Editor.
-- Uses public.profiles.lootix_available as the spendable RL Coins balance.

create table if not exists public.partner_reward_transactions (
  id bigint generated by default as identity primary key,
  provider text not null,
  transaction_id text not null,
  user_id uuid not null,
  offer_id text,
  status text not null,
  amount_usd numeric(12,6) not null default 0,
  reward_coins bigint not null default 0,
  credited boolean not null default false,
  reversed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(provider, transaction_id)
);

alter table public.partner_reward_transactions enable row level security;
-- No client policies: only service-role/server access.

create or replace function public.apply_partner_reward(
  p_provider text,
  p_transaction_id text,
  p_user_id uuid,
  p_offer_id text,
  p_status text,
  p_amount_usd numeric,
  p_reward_coins bigint
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  tx public.partner_reward_transactions%rowtype;
  delta bigint := 0;
begin
  if p_provider <> 'cpx' then raise exception 'unsupported provider'; end if;
  if p_transaction_id is null or length(p_transaction_id) = 0 then raise exception 'missing transaction id'; end if;
  if p_reward_coins < 0 then raise exception 'invalid reward'; end if;

  insert into public.partner_reward_transactions(provider, transaction_id, user_id, offer_id, status, amount_usd, reward_coins)
  values (p_provider, p_transaction_id, p_user_id, p_offer_id, p_status, p_amount_usd, p_reward_coins)
  on conflict (provider, transaction_id) do nothing;

  select * into tx from public.partner_reward_transactions
   where provider=p_provider and transaction_id=p_transaction_id
   for update;

  if tx.user_id <> p_user_id then raise exception 'transaction user mismatch'; end if;

  if p_status = '1' and not tx.credited and not tx.reversed then
    update public.profiles set lootix_available = coalesce(lootix_available,0) + tx.reward_coins where id = tx.user_id;
    if not found then raise exception 'user profile not found'; end if;
    delta := tx.reward_coins;
    update public.partner_reward_transactions set credited=true, status=p_status, updated_at=now()
      where id=tx.id;
  elsif p_status = '2' and tx.credited and not tx.reversed then
    update public.profiles set lootix_available = greatest(0, coalesce(lootix_available,0) - tx.reward_coins) where id = tx.user_id;
    if not found then raise exception 'user profile not found'; end if;
    delta := -tx.reward_coins;
    update public.partner_reward_transactions set reversed=true, status=p_status, updated_at=now()
      where id=tx.id;
  else
    update public.partner_reward_transactions set status=p_status, updated_at=now() where id=tx.id;
  end if;

  return jsonb_build_object('ok',true,'transaction_id',p_transaction_id,'delta',delta);
end;
$$;

revoke all on function public.apply_partner_reward(text,text,uuid,text,text,numeric,bigint) from public;
revoke all on function public.apply_partner_reward(text,text,uuid,text,text,numeric,bigint) from anon;
revoke all on function public.apply_partner_reward(text,text,uuid,text,text,numeric,bigint) from authenticated;
grant execute on function public.apply_partner_reward(text,text,uuid,text,text,numeric,bigint) to service_role;
