(() => {
'use strict';
if(window.__RL_USERNAME_GUARD_V14__)return;window.__RL_USERNAME_GUARD_V14__=true;
const $=id=>document.getElementById(id),clean=v=>String(v||'').trim(),valid=v=>/^[A-Za-z0-9_-]{3,20}$/.test(clean(v));
function patchExistingAccountSignup(){if(typeof sb==='undefined'||!sb?.auth?.signUp||sb.auth.signUp.__rlExistingAccountPatched)return;const original=sb.auth.signUp.bind(sb.auth);const wrapped=async credentials=>{const result=await original(credentials),ids=result?.data?.user?.identities;if(!result?.error&&Array.isArray(ids)&&ids.length===0)return {data:{user:null,session:null},error:new Error('Un compte existe déjà avec cette adresse e-mail. Utilise « Se connecter ».')};return result};wrapped.__rlExistingAccountPatched=true;sb.auth.signUp=wrapped;}
async function available(username){try{const {data,error}=await sb.rpc('username_available',{p_username:clean(username)});return error?{setup:true}:{setup:false,unavailable:data!==true}}catch(_){return {setup:true}}}
async function claim(username){try{const normalized=clean(username),{data,error}=await sb.rpc('claim_username',{p_username:normalized});if(error||!data?.ok)return {ok:false,error:data?.error||'setup'};const current=(await sb.auth.getSession())?.data?.session?.user;if(clean(current?.user_metadata?.username)!==normalized||clean(current?.user_metadata?.player_name)!==normalized){const auth=await sb.auth.updateUser({data:{username:normalized,player_name:normalized}});if(auth?.error)return {ok:false,error:'auth'}}return {ok:true}}catch(_){return {ok:false,error:'setup'}}}
function installAvailabilityHint(){const input=$('usernameInput');if(!input||$('usernameAvailability'))return;const hint=document.createElement('div');hint.id='usernameAvailability';hint.style.cssText='font-size:11px;margin:-7px 0 12px;min-height:14px';input.insertAdjacentElement('afterend',hint);let seq=0;input.addEventListener('input',()=>{const mine=++seq,value=clean(input.value);if(!valid(value)){hint.textContent='';return}hint.textContent='Vérification du pseudo…';setTimeout(async()=>{if(mine!==seq)return;const r=await available(value);if(mine!==seq||r.setup){hint.textContent='';return}hint.textContent=r.unavailable?'❌ Ce pseudo est déjà pris.':'✓ Pseudo disponible.';hint.style.color=r.unavailable?'#ff6d72':'#57df87'},300)})}
function protectSignup(){const btn=$('signupAction');if(!btn||btn.dataset.uniqueUsernameGuard==='1')return;btn.dataset.uniqueUsernameGuard='1';btn.addEventListener('click',async event=>{if(btn.dataset.uniqueUsernameGuard==='pass'){btn.dataset.uniqueUsernameGuard='1';return}const username=clean($('usernameInput')?.value);if(!valid(username))return;event.preventDefault();event.stopImmediatePropagation();btn.disabled=true;const check=await available(username);btn.disabled=false;if(check.setup){alert('La vérification du pseudo est momentanément indisponible.');return}if(check.unavailable){alert('Ce pseudo est déjà utilisé.');$('usernameInput')?.focus();return}btn.dataset.uniqueUsernameGuard='pass';btn.click()},true)}
function protectLegacyClaim(){document.addEventListener('click',async event=>{const btn=event.target.closest('#rlSavePseudo');if(!btn)return;const input=$('rlLegacyPseudo'),username=clean(input?.value);if(!valid(username))return;event.preventDefault();event.stopImmediatePropagation();btn.disabled=true;const result=await claim(username);btn.disabled=false;if(!result.ok){alert(result.error==='username_taken'?'Ce pseudo est déjà utilisé.':'Impossible de réserver ce pseudo pour le moment.');return}$('rlPseudoOverlay')?.remove()},true)}
function boot(){patchExistingAccountSignup();protectSignup();protectLegacyClaim();installAvailabilityHint();}
// V14: no getSession, profile write, leaderboard load or auth listener at page boot.
// Network work happens only when the user actually checks/claims a username.
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();